version: '3.8'
services:
  mongo:
    container_name: xetienchuyen
    image: mongo
    environment:
      - MONGO_DATABASE="xetienchuyen"
    ports:
      - 27017:27017
  mongo-express:
    container_name: xetienchuyen-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081
